### ISSUE TITLE
enable CORS

### ISSUE THREAD

**Issue by rolandjitsu** [aunyks/newton-api#1]
I was just trying your API with Angular 2 HTTP, but it seems that you do not have CORS enabled, so my XHR fails with:
`XMLHttpRequest cannot load https://newton.now.sh/sin/8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access`.

**Comment by aunyks** [comment]
Ah, I see the error. I'm on it right now.

**Comment by aunyks** [comment]
There we go! The most recent commit should fix that for you. Check your app again and let me know if the problem persists.

**Comment by rolandjitsu** [comment]
Thanks 👍
