### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by jfoggo** [aunyks/newton-api#17]
You might want to add the [Telegram BOT](https://t.me/sir_newton_bot) to the section "What have people made"? The bot uses the [now.sh](https://newton.now.sh) REST API.

By the way: very cool API !!! 

Warm regards,
Julian

**Comment by aunyks** [comment]
Done! Thanks for your help.

**Comment by darshantejani007** [comment]
Hi @jfoggo , That's a good bot. Can you let me know which libraries you used for the bot?
