### ISSUE TITLE
Factor/ x^2 + 10x + 25

### ISSUE THREAD

**Issue by zenraiching** [aunyks/newton-api#20]
![image](https://user-images.githubusercontent.com/39197883/100692795-8d2cd980-33c6-11eb-9623-e38e78161410.png)

My equation is 
`Factor/ **x^2 + 10x + 25**`

it doesn't show the "+" sign in the API
I think it response this as a concatenation, that's why It produces this kind of result

**Comment by AldanTanneo** [comment]
You need to encode your "+" signs in URL format, like so:
`factor/x^2 %2B 10x %2B 25`
![image](https://user-images.githubusercontent.com/64717124/101860230-a1629a80-3b6d-11eb-9dfb-5a4744b22010.png)

**Comment by zenraiching** [comment]
Thank you @AldanTanneo
