### ISSUE TITLE
 I have different answers on my postman response 

### ISSUE THREAD

**Issue by fiqryq** [aunyks/newton-api#29]
hello I have some issues, I have different answers on my postman response 

i try use this example :
![Screen Shot 2021-09-30 at 15 42 04](https://user-images.githubusercontent.com/25787603/135419142-74c04cce-2db4-4618-99ac-9ceaafad40af.png)

it must be returned 8 but on my postman i got 16 just like this : 

<img width="1011" alt="Screen Shot 2021-09-30 at 15 45 51" src="https://user-images.githubusercontent.com/25787603/135419384-c0130d56-1d3b-4b0f-96d7-dac31a862532.png">

and I also try mathway and returned 8 
![Screen Shot 2021-09-30 at 15 47 25](https://user-images.githubusercontent.com/25787603/135419708-517ab344-7f27-4717-ac71-afbf2cdb8d63.png)

**Comment by aunyks** [comment]
Hi! Please try url-encoding the plus sign with `%2b`.

**Comment by fiqryq** [comment]
hoo i see thank you
