### ISSUE TITLE
to compute fractions or exponentitation,just use the RegExp&& replace(),such as 

### ISSUE THREAD

**Issue by apenshar** [aunyks/newton-api#5]
str.replace(/(\/)|÷/,"(over)").replace(/∧/g,"^");

**Comment by aunyks** [comment]
@apenshar For fractions, I cannot interpret them using the `/`, because the browser or other url parser interprets that as a url path. As for the exponentiation, I'll give that some thought and get back to you. Thanks for opening an issue!
