### ISSUE TITLE
Endpoint mixups?

### ISSUE THREAD

**Issue by TheWithz** [aunyks/newton-api#6]
I noticed that some of my python scripts that use the api were throwing errors. when viewing the endpoint `https://newton.now.sh/factor/x%5E2-9` the responce is `{"operation":"factor",
"expression":"x^2-9",
"result":"-5"}` Not sure what could be wrong here. 

Another example `https://newton.now.sh/derive/x%5E2` shows `{"operation":"derive",
"expression":"x^2",
"result":"0"}`

**Comment by TheWithz** [comment]
Edit: looks like the problem might be with [MetaData](https://github.com/metadelta/metadelta)

**Comment by aunyks** [comment]
@TheWithz I changed some things on Now. Try it again and let me know if the problem persists.

**Comment by TheWithz** [comment]
All good now! Thanks for the quick response.
